name: CI
# Wann soll die Action ausgeführt werden?
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Testschritt
      - name: Test workflow
        run: echo "GitHub Actions is running!"

      - name: Build C application
        working-directory: proj
        run: make build